# ============================================================
#  Research Collaboration System - Application Config
# ============================================================

# Server
server.port=8080

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/research_collab?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=Asia/Kolkata&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=yatin1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Email (Gmail SMTP - for Observer pattern notifications)
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sumakkiyatin@gmail.com
spring.mail.password=wjuokjfyteeccjnk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# n8n Webhook URL (for email notification workflow)
n8n.webhook.url=https://1cd6-223-31-218-223.ngrok-free.app/webhook/research-update

# Application
app.name=Research Collaboration System
app.version=1.0.0

# Logging
logging.level.com.research=INFO
logging.level.org.springframework.security=WARN
